// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class BallCollisionResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):BallCollisionResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsBallCollisionResponse(bb:flatbuffers.ByteBuffer, obj?:BallCollisionResponse):BallCollisionResponse {
  return (obj || new BallCollisionResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsBallCollisionResponse(bb:flatbuffers.ByteBuffer, obj?:BallCollisionResponse):BallCollisionResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new BallCollisionResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sessionId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startBallCollisionResponse(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addSessionId(builder:flatbuffers.Builder, sessionId:number) {
  builder.addFieldInt32(0, sessionId, 0);
}

static endBallCollisionResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createBallCollisionResponse(builder:flatbuffers.Builder, sessionId:number):flatbuffers.Offset {
  BallCollisionResponse.startBallCollisionResponse(builder);
  BallCollisionResponse.addSessionId(builder, sessionId);
  return BallCollisionResponse.endBallCollisionResponse(builder);
}
}
