// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class LinearColor {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):LinearColor {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

red():number {
  return this.bb!.readFloat32(this.bb_pos);
}

green():number {
  return this.bb!.readFloat32(this.bb_pos + 4);
}

blue():number {
  return this.bb!.readFloat32(this.bb_pos + 8);
}

alpha():number {
  return this.bb!.readFloat32(this.bb_pos + 12);
}

static sizeOf():number {
  return 16;
}

static createLinearColor(builder:flatbuffers.Builder, red: number, green: number, blue: number, alpha: number):flatbuffers.Offset {
  builder.prep(4, 16);
  builder.writeFloat32(alpha);
  builder.writeFloat32(blue);
  builder.writeFloat32(green);
  builder.writeFloat32(red);
  return builder.offset();
}

}
