"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.LinearColor = void 0;
var LinearColor = /** @class */ (function () {
    function LinearColor() {
        this.bb = null;
        this.bb_pos = 0;
    }
    LinearColor.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    LinearColor.prototype.red = function () {
        return this.bb.readFloat32(this.bb_pos);
    };
    LinearColor.prototype.green = function () {
        return this.bb.readFloat32(this.bb_pos + 4);
    };
    LinearColor.prototype.blue = function () {
        return this.bb.readFloat32(this.bb_pos + 8);
    };
    LinearColor.prototype.alpha = function () {
        return this.bb.readFloat32(this.bb_pos + 12);
    };
    LinearColor.sizeOf = function () {
        return 16;
    };
    LinearColor.createLinearColor = function (builder, red, green, blue, alpha) {
        builder.prep(4, 16);
        builder.writeFloat32(alpha);
        builder.writeFloat32(blue);
        builder.writeFloat32(green);
        builder.writeFloat32(red);
        return builder.offset();
    };
    return LinearColor;
}());
exports.LinearColor = LinearColor;
//# sourceMappingURL=linear-color.js.map