// automatically generated by the FlatBuffers compiler, do not modify

import { ClientLoginResponse } from '../epschema/client-login-response.js';
import { GenericBatchRequest } from '../epschema/generic-batch-request.js';
import { GenericBatchResponse } from '../epschema/generic-batch-response.js';
import { JsonToBinaryRequest } from '../epschema/json-to-binary-request.js';
import { JsonToBinaryResponse } from '../epschema/json-to-binary-response.js';
import { LinearColorRequest } from '../epschema/linear-color-request.js';
import { LinearColorResponse } from '../epschema/linear-color-response.js';
import { MediaPlaneLoginRequest } from '../epschema/media-plane-login-request.js';
import { MobileToMediaPlaneLoginRequest } from '../epschema/mobile-to-media-plane-login-request.js';
import { MobileToMediaPlaneLogoutRequest } from '../epschema/mobile-to-media-plane-logout-request.js';
import { PingMediaPlaneRequest } from '../epschema/ping-media-plane-request.js';
import { PingMediaPlaneResponse } from '../epschema/ping-media-plane-response.js';
import { PingMediaPlaneUnreliableRequest } from '../epschema/ping-media-plane-unreliable-request.js';
import { PingMediaPlaneUnreliableResponse } from '../epschema/ping-media-plane-unreliable-response.js';
import { PingServerRequest } from '../epschema/ping-server-request.js';
import { PingServerResponse } from '../epschema/ping-server-response.js';
import { PingServerUnreliableRequest } from '../epschema/ping-server-unreliable-request.js';
import { PingServerUnreliableResponse } from '../epschema/ping-server-unreliable-response.js';
import { PlayerTrailRequest } from '../epschema/player-trail-request.js';
import { PlayerTrailResponse } from '../epschema/player-trail-response.js';
import { RepeaterBinaryResponse } from '../epschema/repeater-binary-response.js';
import { RepeaterBroadcastBinaryResponse } from '../epschema/repeater-broadcast-binary-response.js';
import { RepeaterLoginRequest } from '../epschema/repeater-login-request.js';
import { TrailLengthRequest } from '../epschema/trail-length-request.js';
import { TrailLengthResponse } from '../epschema/trail-length-response.js';
import { UseEmissiveRequest } from '../epschema/use-emissive-request.js';
import { UseEmissiveResponse } from '../epschema/use-emissive-response.js';
import { WebClientLoginRequest } from '../epschema/web-client-login-request.js';
import { WebClientLoginResponse } from '../epschema/web-client-login-response.js';
import { WebClientLogoutRequest } from '../epschema/web-client-logout-request.js';


export enum Message {
  NONE = 0,
  PingServerRequest = 1,
  PingServerResponse = 2,
  PingServerUnreliableRequest = 3,
  PingServerUnreliableResponse = 4,
  PingMediaPlaneRequest = 5,
  PingMediaPlaneResponse = 6,
  PingMediaPlaneUnreliableRequest = 7,
  PingMediaPlaneUnreliableResponse = 8,
  ClientLoginResponse = 9,
  MediaPlaneLoginRequest = 10,
  MobileToMediaPlaneLoginRequest = 11,
  MobileToMediaPlaneLogoutRequest = 12,
  JsonToBinaryRequest = 13,
  JsonToBinaryResponse = 14,
  RepeaterLoginRequest = 15,
  WebClientLoginRequest = 16,
  WebClientLoginResponse = 17,
  WebClientLogoutRequest = 18,
  RepeaterBinaryResponse = 19,
  RepeaterBroadcastBinaryResponse = 20,
  GenericBatchRequest = 21,
  GenericBatchResponse = 22,
  LinearColorRequest = 23,
  LinearColorResponse = 24,
  UseEmissiveRequest = 25,
  UseEmissiveResponse = 26,
  PlayerTrailRequest = 27,
  PlayerTrailResponse = 28,
  TrailLengthRequest = 29,
  TrailLengthResponse = 30
}

export function unionToMessage(
  type: Message,
  accessor: (obj:ClientLoginResponse|GenericBatchRequest|GenericBatchResponse|JsonToBinaryRequest|JsonToBinaryResponse|LinearColorRequest|LinearColorResponse|MediaPlaneLoginRequest|MobileToMediaPlaneLoginRequest|MobileToMediaPlaneLogoutRequest|PingMediaPlaneRequest|PingMediaPlaneResponse|PingMediaPlaneUnreliableRequest|PingMediaPlaneUnreliableResponse|PingServerRequest|PingServerResponse|PingServerUnreliableRequest|PingServerUnreliableResponse|PlayerTrailRequest|PlayerTrailResponse|RepeaterBinaryResponse|RepeaterBroadcastBinaryResponse|RepeaterLoginRequest|TrailLengthRequest|TrailLengthResponse|UseEmissiveRequest|UseEmissiveResponse|WebClientLoginRequest|WebClientLoginResponse|WebClientLogoutRequest) => ClientLoginResponse|GenericBatchRequest|GenericBatchResponse|JsonToBinaryRequest|JsonToBinaryResponse|LinearColorRequest|LinearColorResponse|MediaPlaneLoginRequest|MobileToMediaPlaneLoginRequest|MobileToMediaPlaneLogoutRequest|PingMediaPlaneRequest|PingMediaPlaneResponse|PingMediaPlaneUnreliableRequest|PingMediaPlaneUnreliableResponse|PingServerRequest|PingServerResponse|PingServerUnreliableRequest|PingServerUnreliableResponse|PlayerTrailRequest|PlayerTrailResponse|RepeaterBinaryResponse|RepeaterBroadcastBinaryResponse|RepeaterLoginRequest|TrailLengthRequest|TrailLengthResponse|UseEmissiveRequest|UseEmissiveResponse|WebClientLoginRequest|WebClientLoginResponse|WebClientLogoutRequest|null
): ClientLoginResponse|GenericBatchRequest|GenericBatchResponse|JsonToBinaryRequest|JsonToBinaryResponse|LinearColorRequest|LinearColorResponse|MediaPlaneLoginRequest|MobileToMediaPlaneLoginRequest|MobileToMediaPlaneLogoutRequest|PingMediaPlaneRequest|PingMediaPlaneResponse|PingMediaPlaneUnreliableRequest|PingMediaPlaneUnreliableResponse|PingServerRequest|PingServerResponse|PingServerUnreliableRequest|PingServerUnreliableResponse|PlayerTrailRequest|PlayerTrailResponse|RepeaterBinaryResponse|RepeaterBroadcastBinaryResponse|RepeaterLoginRequest|TrailLengthRequest|TrailLengthResponse|UseEmissiveRequest|UseEmissiveResponse|WebClientLoginRequest|WebClientLoginResponse|WebClientLogoutRequest|null {
  switch(Message[type]) {
    case 'NONE': return null; 
    case 'PingServerRequest': return accessor(new PingServerRequest())! as PingServerRequest;
    case 'PingServerResponse': return accessor(new PingServerResponse())! as PingServerResponse;
    case 'PingServerUnreliableRequest': return accessor(new PingServerUnreliableRequest())! as PingServerUnreliableRequest;
    case 'PingServerUnreliableResponse': return accessor(new PingServerUnreliableResponse())! as PingServerUnreliableResponse;
    case 'PingMediaPlaneRequest': return accessor(new PingMediaPlaneRequest())! as PingMediaPlaneRequest;
    case 'PingMediaPlaneResponse': return accessor(new PingMediaPlaneResponse())! as PingMediaPlaneResponse;
    case 'PingMediaPlaneUnreliableRequest': return accessor(new PingMediaPlaneUnreliableRequest())! as PingMediaPlaneUnreliableRequest;
    case 'PingMediaPlaneUnreliableResponse': return accessor(new PingMediaPlaneUnreliableResponse())! as PingMediaPlaneUnreliableResponse;
    case 'ClientLoginResponse': return accessor(new ClientLoginResponse())! as ClientLoginResponse;
    case 'MediaPlaneLoginRequest': return accessor(new MediaPlaneLoginRequest())! as MediaPlaneLoginRequest;
    case 'MobileToMediaPlaneLoginRequest': return accessor(new MobileToMediaPlaneLoginRequest())! as MobileToMediaPlaneLoginRequest;
    case 'MobileToMediaPlaneLogoutRequest': return accessor(new MobileToMediaPlaneLogoutRequest())! as MobileToMediaPlaneLogoutRequest;
    case 'JsonToBinaryRequest': return accessor(new JsonToBinaryRequest())! as JsonToBinaryRequest;
    case 'JsonToBinaryResponse': return accessor(new JsonToBinaryResponse())! as JsonToBinaryResponse;
    case 'RepeaterLoginRequest': return accessor(new RepeaterLoginRequest())! as RepeaterLoginRequest;
    case 'WebClientLoginRequest': return accessor(new WebClientLoginRequest())! as WebClientLoginRequest;
    case 'WebClientLoginResponse': return accessor(new WebClientLoginResponse())! as WebClientLoginResponse;
    case 'WebClientLogoutRequest': return accessor(new WebClientLogoutRequest())! as WebClientLogoutRequest;
    case 'RepeaterBinaryResponse': return accessor(new RepeaterBinaryResponse())! as RepeaterBinaryResponse;
    case 'RepeaterBroadcastBinaryResponse': return accessor(new RepeaterBroadcastBinaryResponse())! as RepeaterBroadcastBinaryResponse;
    case 'GenericBatchRequest': return accessor(new GenericBatchRequest())! as GenericBatchRequest;
    case 'GenericBatchResponse': return accessor(new GenericBatchResponse())! as GenericBatchResponse;
    case 'LinearColorRequest': return accessor(new LinearColorRequest())! as LinearColorRequest;
    case 'LinearColorResponse': return accessor(new LinearColorResponse())! as LinearColorResponse;
    case 'UseEmissiveRequest': return accessor(new UseEmissiveRequest())! as UseEmissiveRequest;
    case 'UseEmissiveResponse': return accessor(new UseEmissiveResponse())! as UseEmissiveResponse;
    case 'PlayerTrailRequest': return accessor(new PlayerTrailRequest())! as PlayerTrailRequest;
    case 'PlayerTrailResponse': return accessor(new PlayerTrailResponse())! as PlayerTrailResponse;
    case 'TrailLengthRequest': return accessor(new TrailLengthRequest())! as TrailLengthRequest;
    case 'TrailLengthResponse': return accessor(new TrailLengthResponse())! as TrailLengthResponse;
    default: return null;
  }
}

export function unionListToMessage(
  type: Message, 
  accessor: (index: number, obj:ClientLoginResponse|GenericBatchRequest|GenericBatchResponse|JsonToBinaryRequest|JsonToBinaryResponse|LinearColorRequest|LinearColorResponse|MediaPlaneLoginRequest|MobileToMediaPlaneLoginRequest|MobileToMediaPlaneLogoutRequest|PingMediaPlaneRequest|PingMediaPlaneResponse|PingMediaPlaneUnreliableRequest|PingMediaPlaneUnreliableResponse|PingServerRequest|PingServerResponse|PingServerUnreliableRequest|PingServerUnreliableResponse|PlayerTrailRequest|PlayerTrailResponse|RepeaterBinaryResponse|RepeaterBroadcastBinaryResponse|RepeaterLoginRequest|TrailLengthRequest|TrailLengthResponse|UseEmissiveRequest|UseEmissiveResponse|WebClientLoginRequest|WebClientLoginResponse|WebClientLogoutRequest) => ClientLoginResponse|GenericBatchRequest|GenericBatchResponse|JsonToBinaryRequest|JsonToBinaryResponse|LinearColorRequest|LinearColorResponse|MediaPlaneLoginRequest|MobileToMediaPlaneLoginRequest|MobileToMediaPlaneLogoutRequest|PingMediaPlaneRequest|PingMediaPlaneResponse|PingMediaPlaneUnreliableRequest|PingMediaPlaneUnreliableResponse|PingServerRequest|PingServerResponse|PingServerUnreliableRequest|PingServerUnreliableResponse|PlayerTrailRequest|PlayerTrailResponse|RepeaterBinaryResponse|RepeaterBroadcastBinaryResponse|RepeaterLoginRequest|TrailLengthRequest|TrailLengthResponse|UseEmissiveRequest|UseEmissiveResponse|WebClientLoginRequest|WebClientLoginResponse|WebClientLogoutRequest|null, 
  index: number
): ClientLoginResponse|GenericBatchRequest|GenericBatchResponse|JsonToBinaryRequest|JsonToBinaryResponse|LinearColorRequest|LinearColorResponse|MediaPlaneLoginRequest|MobileToMediaPlaneLoginRequest|MobileToMediaPlaneLogoutRequest|PingMediaPlaneRequest|PingMediaPlaneResponse|PingMediaPlaneUnreliableRequest|PingMediaPlaneUnreliableResponse|PingServerRequest|PingServerResponse|PingServerUnreliableRequest|PingServerUnreliableResponse|PlayerTrailRequest|PlayerTrailResponse|RepeaterBinaryResponse|RepeaterBroadcastBinaryResponse|RepeaterLoginRequest|TrailLengthRequest|TrailLengthResponse|UseEmissiveRequest|UseEmissiveResponse|WebClientLoginRequest|WebClientLoginResponse|WebClientLogoutRequest|null {
  switch(Message[type]) {
    case 'NONE': return null; 
    case 'PingServerRequest': return accessor(index, new PingServerRequest())! as PingServerRequest;
    case 'PingServerResponse': return accessor(index, new PingServerResponse())! as PingServerResponse;
    case 'PingServerUnreliableRequest': return accessor(index, new PingServerUnreliableRequest())! as PingServerUnreliableRequest;
    case 'PingServerUnreliableResponse': return accessor(index, new PingServerUnreliableResponse())! as PingServerUnreliableResponse;
    case 'PingMediaPlaneRequest': return accessor(index, new PingMediaPlaneRequest())! as PingMediaPlaneRequest;
    case 'PingMediaPlaneResponse': return accessor(index, new PingMediaPlaneResponse())! as PingMediaPlaneResponse;
    case 'PingMediaPlaneUnreliableRequest': return accessor(index, new PingMediaPlaneUnreliableRequest())! as PingMediaPlaneUnreliableRequest;
    case 'PingMediaPlaneUnreliableResponse': return accessor(index, new PingMediaPlaneUnreliableResponse())! as PingMediaPlaneUnreliableResponse;
    case 'ClientLoginResponse': return accessor(index, new ClientLoginResponse())! as ClientLoginResponse;
    case 'MediaPlaneLoginRequest': return accessor(index, new MediaPlaneLoginRequest())! as MediaPlaneLoginRequest;
    case 'MobileToMediaPlaneLoginRequest': return accessor(index, new MobileToMediaPlaneLoginRequest())! as MobileToMediaPlaneLoginRequest;
    case 'MobileToMediaPlaneLogoutRequest': return accessor(index, new MobileToMediaPlaneLogoutRequest())! as MobileToMediaPlaneLogoutRequest;
    case 'JsonToBinaryRequest': return accessor(index, new JsonToBinaryRequest())! as JsonToBinaryRequest;
    case 'JsonToBinaryResponse': return accessor(index, new JsonToBinaryResponse())! as JsonToBinaryResponse;
    case 'RepeaterLoginRequest': return accessor(index, new RepeaterLoginRequest())! as RepeaterLoginRequest;
    case 'WebClientLoginRequest': return accessor(index, new WebClientLoginRequest())! as WebClientLoginRequest;
    case 'WebClientLoginResponse': return accessor(index, new WebClientLoginResponse())! as WebClientLoginResponse;
    case 'WebClientLogoutRequest': return accessor(index, new WebClientLogoutRequest())! as WebClientLogoutRequest;
    case 'RepeaterBinaryResponse': return accessor(index, new RepeaterBinaryResponse())! as RepeaterBinaryResponse;
    case 'RepeaterBroadcastBinaryResponse': return accessor(index, new RepeaterBroadcastBinaryResponse())! as RepeaterBroadcastBinaryResponse;
    case 'GenericBatchRequest': return accessor(index, new GenericBatchRequest())! as GenericBatchRequest;
    case 'GenericBatchResponse': return accessor(index, new GenericBatchResponse())! as GenericBatchResponse;
    case 'LinearColorRequest': return accessor(index, new LinearColorRequest())! as LinearColorRequest;
    case 'LinearColorResponse': return accessor(index, new LinearColorResponse())! as LinearColorResponse;
    case 'UseEmissiveRequest': return accessor(index, new UseEmissiveRequest())! as UseEmissiveRequest;
    case 'UseEmissiveResponse': return accessor(index, new UseEmissiveResponse())! as UseEmissiveResponse;
    case 'PlayerTrailRequest': return accessor(index, new PlayerTrailRequest())! as PlayerTrailRequest;
    case 'PlayerTrailResponse': return accessor(index, new PlayerTrailResponse())! as PlayerTrailResponse;
    case 'TrailLengthRequest': return accessor(index, new TrailLengthRequest())! as TrailLengthRequest;
    case 'TrailLengthResponse': return accessor(index, new TrailLengthResponse())! as TrailLengthResponse;
    default: return null;
  }
}
