// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class TrailLengthResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TrailLengthResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTrailLengthResponse(bb:flatbuffers.ByteBuffer, obj?:TrailLengthResponse):TrailLengthResponse {
  return (obj || new TrailLengthResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTrailLengthResponse(bb:flatbuffers.ByteBuffer, obj?:TrailLengthResponse):TrailLengthResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TrailLengthResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sessionId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

length():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startTrailLengthResponse(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addSessionId(builder:flatbuffers.Builder, sessionId:number) {
  builder.addFieldInt32(0, sessionId, 0);
}

static addLength(builder:flatbuffers.Builder, length:number) {
  builder.addFieldFloat32(1, length, 0.0);
}

static endTrailLengthResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createTrailLengthResponse(builder:flatbuffers.Builder, sessionId:number, length:number):flatbuffers.Offset {
  TrailLengthResponse.startTrailLengthResponse(builder);
  TrailLengthResponse.addSessionId(builder, sessionId);
  TrailLengthResponse.addLength(builder, length);
  return TrailLengthResponse.endTrailLengthResponse(builder);
}
}
