// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class UseEmissiveRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):UseEmissiveRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUseEmissiveRequest(bb:flatbuffers.ByteBuffer, obj?:UseEmissiveRequest):UseEmissiveRequest {
  return (obj || new UseEmissiveRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUseEmissiveRequest(bb:flatbuffers.ByteBuffer, obj?:UseEmissiveRequest):UseEmissiveRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new UseEmissiveRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sessionId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

useEmissive():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startUseEmissiveRequest(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addSessionId(builder:flatbuffers.Builder, sessionId:number) {
  builder.addFieldInt32(0, sessionId, 0);
}

static addUseEmissive(builder:flatbuffers.Builder, useEmissive:boolean) {
  builder.addFieldInt8(1, +useEmissive, +false);
}

static endUseEmissiveRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createUseEmissiveRequest(builder:flatbuffers.Builder, sessionId:number, useEmissive:boolean):flatbuffers.Offset {
  UseEmissiveRequest.startUseEmissiveRequest(builder);
  UseEmissiveRequest.addSessionId(builder, sessionId);
  UseEmissiveRequest.addUseEmissive(builder, useEmissive);
  return UseEmissiveRequest.endUseEmissiveRequest(builder);
}
}
